FROM ubuntu:latest
LABEL authors="rkagupta"

# Set the working directory inside the container
WORKDIR /app

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Copy the Python script into the container
COPY attack.py .

COPY requirements.txt .

RUN pip install --break-system-packages -r requirements.txt

# Command to run the Python server
CMD ["python3", "attack.py", "--host=127.0.0.1", "--port=31110", "--timeout=100", "--num_threads=10"]