apiVersion: v1
kind: Service
metadata:
  name: dns-gatekeeper
  namespace: default
spec:
  selector:
    app: dns-gatekeeper
  type: ClusterIP
  ports:
    - name: udp
      port: 31110
      targetPort: 31110
      protocol: UDP